# Deep Neural Net Basics

### Packages

In [1]:
import numpy as np
import h5py
import matplotlib.pyplot as plt
from test_cases import *
from dnn_utils import sigmoid, sigmoid_backward, relu, relu_backward

%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

np.random.seed(1)

## Helper Functions 
### Initialize Parameters Example - For A 2 Layer Network

In [2]:
def initialize_parameters(n_x, n_h, n_y):
    """
    Arguements:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    parameters -- a python dictionary containing the following params
                  W1 -- weight matrix of shape (n_h, n_x)
                  b1 -- bias vector of shape (n_h, 1)
                  W2 -- weight matric of shape (n_y, n_h)
                  b2 -- bias vector of shape (n_y, 1)
    """
    ## To match the examples
    np.random.seed(1)
    
    W1 = np.random.randn(n_h, n_x)*0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h)*0.01
    b2 = np.zeros((n_y, 1))
    
    assert(W1.shape == (n_h, n_x))
    assert(b1.shape == (n_h, 1))
    assert(W2.shape == (n_y, n_h))
    assert(b2.shape == (n_y, 1))
    
    parameters = {"W1":W1,
                  "b1":b1,
                  "W2":W2,
                  "b2":b2}
    
    return parameters

In [3]:
## Check Output
parameters = initialize_parameters(3,2,1)
print("W1 = "+str(parameters["W1"]))
print("b1 = "+str(parameters["b1"]))
print("W2 = "+str(parameters["W2"]))
print("b2 = "+str(parameters["b2"]))

W1 = [[ 0.01624345 -0.00611756 -0.00528172]
 [-0.01072969  0.00865408 -0.02301539]]
b1 = [[ 0.]
 [ 0.]]
W2 = [[ 0.01744812 -0.00761207]]
b2 = [[ 0.]]


### Initialize Parameters for an L-Layer Network

In [4]:
def initialize_parameters_deep(layer_dims):
    """
    Initialize parameters for each layer in a deep net
    
    Arguments:
    layer_dims -- A python array containing the dimensions of each layer in the network
    
    Returns:
    parameters -- A python dictionary containing your parameters. "W1", "b1"... "WL","bL"
                  W1 -- a weight matrix of shape (layer_dims[l], layer_dims[l-1])
                  b1 -- a vector of shape (layer_dims[l], 1)
    
    """
    
    np.random.seed(3)
    parameters = {}
    
    # Number of Layers in the network
    L = len(layer_dims) 
    
    for l in range(1, L):
        parameters["W"+str(l)] = np.random.randn(layer_dims[l],layer_dims[l-1])*0.01
        parameters["b"+str(l)] = np.zeros((layer_dims[l], 1))
        
        assert(parameters["W"+str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters["b"+str(l)].shape == (layer_dims[l], 1))
    
    return parameters

In [5]:
parameters = initialize_parameters_deep([5,4,3])
print(parameters["W1"])
print(parameters["b1"])
print(parameters["W2"])
print(parameters["b2"])

[[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]]
[[ 0.]
 [ 0.]
 [ 0.]]


## Forward Propagation
This will done in 3 steps (although it can be done in less steps, we separate them out for this demonstration
- Linear Forward
- Linear Activation Forward
- Linear Model

### Linear Forward

In [6]:
def linear_forward(A, W, b):
    """
    Implement the linear part a layers forward propagation step
    
    Arguments:
    A -- activations from the previous layer (or input layer)
    W -- weight matrix
    b -- bias vector
    
    Returns:
    Z - the input of the activation function, also called the pre-activation
    cache - a python dictionary containing A,W,b for back prop
    """
    
    Z = np.dot(W, A) + b
    assert(Z.shape == (W.shape[0], A.shape[1]))
    
    cache = (A, W, b)
    
    return Z, cache

In [7]:
A, W, b = linear_forward_test_case()
Z, linear_cache = linear_forward(A, W, b)
print("Z" + str(Z))

Z[[ 3.26295337 -1.23429987]]


### Linear Forward Activation

In [8]:
def linear_forward_activation(A_prev, W, b, activation):
    """
    Implement the forward propagation Linear -> Activation
    
    Arguments:
    A_prev -- activations from the previous layer or the input layer
    W -- weight matrix
    b -- bias vector
    activation -- sigmoid or relu stored as string
    
    Returns:
    A -- the output of the activation function, also called the post-activation value
    cache -- a pyton dictionary containing linear_cache and activation_cache for back prop
    """
    
    Z, linear_cache = linear_forward(A_prev, W, b)
    
    if activation == 'sigmoid':
        A, activation_cache = sigmoid(Z)
    
    elif activation == 'relu':
        A, activation_cache = relu(Z)
    
    assert(A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, activation_cache)
    
    return A, cache

In [9]:
A_prev, W, b = linear_activation_forward_test_case()

A, linear_activation_cache = linear_forward_activation(A_prev, W, b, 'sigmoid')
print("With Sigmoid: A = " + str(A))

A, linear_activation_cache = linear_forward_activation(A_prev, W, b, 'relu')
print("With Relu: A = " + str(A))

With Sigmoid: A = [[ 0.96890023  0.11013289]]
With Relu: A = [[ 3.43896131  0.        ]]


### Linear Model
Use the functions implemented above

In [10]:
def L_model_forward(X, parameters):
    """
    Implement forward propagation for the [Linear -> ReLU]*[L-1] -> Linear -> Sigmoid
    
    Arguments:
    X -- data, numpy array of any shape
    parameters -- output of initialize_parameters_deep()
    
    Returns:
    AL -- Last post activation value
    caches -- list of caches containing:
                every cache of linear_relu_forward() (there are L-1 of them, indexed from 0 to L-2)
                the cache of linear_sigmoid_forward() (there is one, indexed L-1)
    """
    
    caches = []
    A = X
    L = len(parameters) // 2
    
    for l in range(1, L):
        A_prev = A
        A, cache = linear_forward_activation(A_prev, parameters["W"+str(l)], parameters["b"+str(l)], 'relu')
        caches.append(cache)
    
    AL, cache = linear_forward_activation(A, parameters["W"+str(L)], parameters["b"+str(L)], 'sigmoid')
    caches.append(cache)    
    
    assert(AL.shape == (1, X.shape[1]))
    return AL, cache    

In [11]:
X, parameters = L_model_forward_test_case_2hidden()
AL, caches = L_model_forward(X, parameters)

print("AL = " + str(AL))
print("Length of Caches List: "+str(len(caches)))

AL = [[ 0.03921668  0.70498921  0.19734387  0.04728177]]
Length of Caches List: 2


## Cost Function

### Implement the cross entropy cost function
formula: $$-\frac{1}{m} \sum\limits_{i = 1}^{m} (y^{(i)}\log\left(a^{[L] (i)}\right) + (1-y^{(i)})\log\left(1- a^{[L](i)}\right)) \tag{7}$$

In [12]:
def compute_cost(AL, Y):
    """
    Implement the cross entropy cost function as represented above to see if the model is really
    learning
    
    Arguments:
    AL - Probability vector corresponding to the labeled prediction vector, shape (1, number of examples)
    Y - true "labeled" vector of shape (1, number of examples)
    
    Returns:
    cost -- crost entropy cost
    """
    
    m = Y.shape[1]
    
    cost = -(1/m) * np.sum(np.multiply(Y, np.log(AL)) + np.multiply(1-Y, np.log(1-AL))) 
    
    #Squeeze a vector into a single numerical outpu
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    return cost
    

In [13]:
Y, AL = compute_cost_test_case()
print(Y, AL)
print("cost = "+str(compute_cost(AL, Y)))

[[1 1 1]] [[ 0.8  0.9  0.4]]
cost = 0.414931599615


## Backpropagation
Similar to Forward propagation this will be demonstrated in 3 steps
- Linear Backward
- Linear Backward Activation
- Linear Model Backward

### Linear Backward

The three outputs $(dW^{[l]}, db^{[l]}, dA^{[l]})$ are computed using the input $dZ^{[l]}$.Here are the formulas you need:
$$ dW^{[l]} = \frac{\partial \mathcal{L} }{\partial W^{[l]}} = \frac{1}{m} dZ^{[l]} A^{[l-1] T} \tag{8}$$
$$ db^{[l]} = \frac{\partial \mathcal{L} }{\partial b^{[l]}} = \frac{1}{m} \sum_{i = 1}^{m} dZ^{[l](i)}\tag{9}$$
$$ dA^{[l-1]} = \frac{\partial \mathcal{L} }{\partial A^{[l-1]}} = W^{[l] T} dZ^{[l]} \tag{10}$$


In [14]:
def linear_backward(dZ, cache):
    """
    Implement the linear portion of backward propagation for a single layer
    
    Arguments:
    dZ - Gradient of the cost with respect to the activation of the current layer
    cache - tuple (A_prev, W, b) from the forward propagation step of the current layer
    
    Returns:
    dA_prev -- Gradient of the cost with respect to the activation of the previous layer l-1
    dW - Gradient of cost with respect to W
    db - Gradient of cost with respect to b
    """
    
    A_prev, W, b = cache
    m = A_prev.shape[1]
    
    dW = (1/m) * np.dot(dZ, A_prev.T)
    db = (1/m) * np.sum(dZ, axis=1, keepdims=True)
    dA_prev = np.dot(W.T, dZ)
    
    assert(dA_prev.shape == A_prev.shape)
    assert(dW.shape == W.shape)
    assert(db.shape == b.shape)
    
    return dA_prev, dW, db

In [15]:
dZ, cache = linear_backward_test_case()
dA_prev, dW, db = linear_backward(dZ, cache)

print ("dA_prev = "+ str(dA_prev))
print ("dW = " + str(dW))
print ("db = " + str(db))

dA_prev = [[ 0.51822968 -0.19517421]
 [-0.40506361  0.15255393]
 [ 2.37496825 -0.89445391]]
dW = [[-0.10076895  1.40685096  1.64992505]]
db = [[ 0.50629448]]


### Linear Backward Activation

In [16]:
def linear_backward_activation(dA, cache, activation):
    """
    Implement the backward propagation step for the Linear -> Activation Layer
    
    Arguments:
    dA -- post activation gradient for current layer l
    cache -- tuple of values (linear_cache, activation_cache) we store for computing back prop
    activation -- the activation used in this layer
    
    Returns:
    dA_prev -- gradient of the cost with respect to activation of the previous layer
    dW -- gradient of cost with respect to W for the current layer
    db -- gradient of cost with respect to b for the current layer
    """
    
    linear_cache, activation_cache = cache
    
    if activation == 'relu':
        dZ = relu_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
    elif activation  == 'sigmoid':
        dZ = sigmoid_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
        
    return dA_prev, dW, db

In [17]:
AL, linear_activation_cache = linear_activation_backward_test_case()

dA_prev, dW, db = linear_backward_activation(AL, linear_activation_cache, activation = "sigmoid")
print ("sigmoid:")
print ("dA_prev = "+ str(dA_prev))
print ("dW = " + str(dW))
print ("db = " + str(db) + "\n")

dA_prev, dW, db = linear_backward_activation(AL, linear_activation_cache, activation = "relu")
print ("relu:")
print ("dA_prev = "+ str(dA_prev))
print ("dW = " + str(dW))
print ("db = " + str(db))

sigmoid:
dA_prev = [[ 0.11017994  0.01105339]
 [ 0.09466817  0.00949723]
 [-0.05743092 -0.00576154]]
dW = [[ 0.10266786  0.09778551 -0.01968084]]
db = [[-0.05729622]]

relu:
dA_prev = [[ 0.44090989 -0.        ]
 [ 0.37883606 -0.        ]
 [-0.2298228   0.        ]]
dW = [[ 0.44513824  0.37371418 -0.10478989]]
db = [[-0.20837892]]


### Linear Model Backward

In [18]:
def L_model_backward(AL, Y, caches):
    """
    Implement the backward propagation for the [LINEAR->RELU] * (L-1) -> LINEAR -> SIGMOID group
    
    Arguments:
    AL -- probability vector, output of the forward propagation (L_model_forward())
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat)
    caches -- list of caches containing:
                every cache of linear_activation_forward() with "relu" (it's caches[l], for l in range(L-1) i.e l = 0...L-2)
                the cache of linear_activation_forward() with "sigmoid" (it's caches[L-1])
    
    Returns:
    grads -- A dictionary with the gradients
             grads["dA" + str(l)] = ... 
             grads["dW" + str(l)] = ...
             grads["db" + str(l)] = ... 
    """
    
    grads = {}
    L = len(caches)
    m = AL.shape[1]
    Y = Y.reshape(AL.shape)
    
    dAL = -(np.divide(Y,AL) - np.divide(1-Y, 1-AL))
    
    current_cache = caches[L-1]
    grads["dA"+str(L)], grads["dW"+str(L)], grads["db"+str(L)] = linear_backward_activation(dAL, current_cache, 'sigmoid')
    
    for l in reversed(range(L-1)):
        current_cache = caches[l]
        dA_prev_temp, dW_temp, db_temp = linear_backward_activation(grads["dA"+str(l+2)], current_cache, 'relu')
        grads["dA"+str(l+1)] = dA_prev_temp
        grads["dW"+str(l+1)] = dW_temp
        grads["db"+str(l+1)] = db_temp
    
    return grads

In [19]:
AL, Y_assess, caches = L_model_backward_test_case()
grads = L_model_backward(AL, Y_assess, caches)
print_grads(grads)

dW1 = [[ 0.41010002  0.07807203  0.13798444  0.10502167]
 [ 0.          0.          0.          0.        ]
 [ 0.05283652  0.01005865  0.01777766  0.0135308 ]]
db1 = [[-0.22007063]
 [ 0.        ]
 [-0.02835349]]
dA1 = [[ 0.12913162 -0.44014127]
 [-0.14175655  0.48317296]
 [ 0.01663708 -0.05670698]]


## Use Gradient Descent To Update Parameters

In [20]:
def update_parameters(parameters, grads, learning_rate):
    """
    Update parameters using Gradient Descent
    
    Arguments:
    parameters -- python dict containing params
    grads -- python dict containing gradients
    learning_rate -- 
    
    Returns:
    parameters -- updated parameters
    """
    
    L = len(parameters) // 2
    
    for l in range(L):
        parameters["W"+str(l+1)] = parameters["W"+str(l+1)] - learning_rate*grads["dW"+str(l+1)]
        parameters["b"+str(l+1)] = parameters["b"+str(l+1)] - learning_rate*grads["db"+str(l+1)]
    
    return parameters

In [21]:
parameters, grads = update_parameters_test_case()
parameters = update_parameters(parameters, grads, 0.1)

print ("W1 = "+ str(parameters["W1"]))
print ("b1 = "+ str(parameters["b1"]))
print ("W2 = "+ str(parameters["W2"]))
print ("b2 = "+ str(parameters["b2"]))

W1 = [[-0.59562069 -0.09991781 -2.14584584  1.82662008]
 [-1.76569676 -0.80627147  0.51115557 -1.18258802]
 [-1.0535704  -0.86128581  0.68284052  2.20374577]]
b1 = [[-0.04659241]
 [-1.28888275]
 [ 0.53405496]]
W2 = [[-0.55569196  0.0354055   1.32964895]]
b2 = [[-0.84610769]]
